Feature/select states
digipolisantwerp/acpaas-ui_react pull request #161
Opened 2020-09-10 09:06 UTC by HybridFox

## PR Checklist

This PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] A changelog entry has been added to CHANGELOG.md if necessary

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] react application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

no statz-e

Issue Number: N/A

## What is the new behavior?
state

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

## Resolved issues

2020-09-11 12:26 UTC, vademo approved these changes

2020-09-15 09:39 UTC, MichaelCastiau requested changes

2020-09-15 09:39 UTC, MichaelCastiau commented on packages/form/Readme.md
> +<Select label="District"
Please add <br/> in between selects.

2020-09-16 08:24 UTC, TriangleJuice approved these changes

2020-09-16 08:35 UTC, MichaelCastiau approved these changes

2020-09-16 09:22 UTC, merged