Bug/autocomplete
digipolisantwerp/acpaas-ui_react pull request #165
Opened 2020-09-15 08:31 UTC by MichaelCastiau

@HybridFox  This PR fixes the handling of the default values

2020-09-15 08:34 UTC, MichaelCastiau commented
@TriangleJuice  Die switch test faalt nog steeds, maar heeft niets met deze PR te maken, moeten wij dat niet aanpakken?

2020-09-15 10:04 UTC, vademo requested changes

2020-09-15 10:04 UTC, vademo commented on packages/autocomplete/Readme.md
> +const defaultValues = ["mechelen", "antwerpen"];
Steden best met een hoofdletter

2020-09-15 10:04 UTC, vademo commented on packages/autocomplete/Readme.md
> +  placeholder="Zoek...">
Mix van engels en Nederlands best gelijktrekken

2020-09-15 11:36 UTC, MichaelCastiau commented on packages/autocomplete/Readme.md
> +const defaultValues = ["mechelen", "antwerpen"];
Dat zijn niet de labels van de steden maar de "value" van een label/value pair.

2020-09-15 11:37 UTC, vademo approved these changes

2020-09-15 13:23 UTC, TriangleJuice requested changes
Could it be that you still need to add the `required` attribute to the autocomplete's input field?

2020-09-16 07:34 UTC, TriangleJuice approved these changes

2020-09-16 13:13 UTC, frankdsm approved these changes

2020-09-16 13:14 UTC, merged