Fix clearing field in sync search dissapearing items
digipolisantwerp/acpaas-ui_react pull request #169
Opened 2020-09-17 09:24 UTC by MichaelCastiau

2020-09-17 09:25 UTC, MichaelCastiau commented
@TriangleJuice  I added a unit tests to test the specific fix for the bug, but there are still two other unit tests failing, that are not related to my work.

2020-09-17 11:59 UTC, TriangleJuice requested changes

2020-09-17 11:59 UTC, TriangleJuice commented on CHANGELOG.md
> +- No more dissapearing elements when selecting item synchrounously and clearing field
```suggestion
- 'Autocomplete' Fixed disappearing elements after selecting item synchronously and clearing field
```

2020-09-17 12:20 UTC, TriangleJuice approved these changes

2020-09-21 07:14 UTC, vademo approved these changes

2020-09-22 08:58 UTC, merged