feat: Allow textarea to use native errors
digipolisantwerp/acpaas-ui_react pull request #171
Opened 2020-09-24 08:14 UTC by Pruxis

## PR Checklist

This PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] A changelog entry has been added to CHANGELOG.md if necessary

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] react application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

## Resolved issues

2020-09-24 08:58 UTC, MichaelCastiau requested changes
onInvalidCapture is not a native react event and is part of the React advanced form library. We do not use this functionality and as far as I know ,we don't have plans to include this library.

2020-09-24 09:25 UTC, Pruxis commented
@MichaelCastiau I am not using any form library, this is native code.

React typings for regular inputs to support these fields: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17082/files
It maps directly to the oninvalid event on an input field https://www.w3schools.com/JSREF/event_oninvalid.asp

2020-10-02 09:38 UTC, MichaelCastiau approved these changes

2020-10-02 09:41 UTC, TriangleJuice approved these changes

2020-10-05 08:14 UTC, merged